version: "3.9"

services:
  # MariaDB Container
  glpidb:
    image: mariadb:10.5
    container_name: glpidb
    hostname: glpidb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=false"
    networks:
      - glpi-net
    env_file:
      - ../.env

  # GLPI Container
  glpi:
    image: diouxx/glpi
    container_name: glpi
    hostname: glpi
    working_dir: "/var/www/html/glpi"
    environment:
      - TIMEZONE=America/Sao_Paulo
      - GLPI_DB_HOST=glpidb
      - GLPI_DB_NAME=${DB_NAME}
      - GLPI_DB_USER=${DB_USER}
      - GLPI_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - glpi_data:/var/www/html/glpi
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.meteoro.rule=Host(`glpi.seudominio.com`)" # Substitua pelo seu domínio
        - "traefik.http.routers.meteoro.entrypoints=websecure"
        - "traefik.http.routers.meteoro.tls.certresolver=myresolver"
        - "traefik.http.services.meteoro.loadbalancer.server.port=80"
    networks:
      - glpi-net
    env_file:
      - ../.env

volumes:
  glpi_data:
  db_data:

networks:
  glpi-net:
    driver: overlay
    external: true
